### PR TITLE
Fix link to imagemin

### PR DESCRIPTION
**Pull request by YoshinoriN**

### CODE REVIEW

**Comment by tomap** [comment]
why not https://github.com/imagemin/imagemin#plugins ?

**Comment by tomap** [comment]
Nope, a link is enough. If someone struggle with this and posts an issue, we'll improve

**Comment by bhaskarmelkani** [comment]
Can you fix the build ?

**Comment by tomap** [comment]
PR #33 fixes it

**Comment by YoshinoriN** [comment]
@tomap Thanks.

@bhaskarmelkani Would you tell me advice? Should I rebase my fix on to latest master & re-pull request ? I’m afraid that I don't familiar with GitHub develop style.

**Comment by tomap** [comment]
Or someone should retrigger the build:)

**Pull request merged**
